AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket with Inventory and Analytics Configurations
Resources:
#Lambda layer bucket
  LambdaLayerBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LambdaLayerBucket:
    Description: database hostname
    Value: !Ref LambdaLayerBucket
    Export:
      Name: !Sub ${AWS::StackName}Name